if(_WIN32ACRYLICHELPER_TOOLCHAIN_CMAKE)
    return()
endif()
set(_WIN32ACRYLICHELPER_TOOLCHAIN_CMAKE 1)

if("${ACRYLIC_TARGET_ARCHITECTURE}" STREQUAL "x86")
    set(CMAKE_SYSTEM_PROCESSOR "i686" CACHE STRING "" FORCE)
elseif("${ACRYLIC_TARGET_ARCHITECTURE}" STREQUAL "x64")
    set(CMAKE_SYSTEM_PROCESSOR "x86_64" CACHE STRING "" FORCE)
elseif("${ACRYLIC_TARGET_ARCHITECTURE}" STREQUAL "arm")
    set(CMAKE_SYSTEM_PROCESSOR "armv7" CACHE STRING "" FORCE)
elseif("${ACRYLIC_TARGET_ARCHITECTURE}" STREQUAL "arm64")
    set(CMAKE_SYSTEM_PROCESSOR "aarch64" CACHE STRING "" FORCE)
endif()

foreach(lang C CXX)
    set(CMAKE_${lang}_COMPILER_TARGET "${CMAKE_SYSTEM_PROCESSOR}-pc-windows-msvc" CACHE STRING "" FORCE)
endforeach()

set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_DEBUG OFF CACHE BOOL "" FORCE)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE ON CACHE BOOL "" FORCE)

set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>" CACHE STRING "" FORCE)

set(CMAKE_C_STANDARD "17" CACHE STRING "" FORCE)
set(CMAKE_C_STANDARD_REQUIRED ON CACHE BOOL "" FORCE)
set(CMAKE_C_EXTENSIONS OFF CACHE BOOL "" FORCE)

set(CMAKE_CXX_STANDARD "17" CACHE STRING "" FORCE)
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "" FORCE)
set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "" FORCE)

#set(CMAKE_C_STANDARD_LIBRARIES "" CACHE STRING "" FORCE)

set(NTDDI_WIN10_19H1 0x0A000007)
# /await:strict /permissive-
set(_common_flags "/await /bigobj /d2FH4 /D_CRT_NON_CONFORMING_SWPRINTFS /D_CRT_SECURE_NO_WARNINGS /D_ENABLE_EXTENDED_ALIGNED_STORAGE /DNOMINMAX /DUNICODE /D_UNICODE /DWIN32 /D_WINDOWS /DWIN32_LEAN_AND_MEAN /DWINRT_LEAN_AND_MEAN /DWINVER=${NTDDI_WIN10_19H1} /D_WIN32_WINNT=${NTDDI_WIN10_19H1} /EHsc /GR- /MP /nologo /utf-8 /W4 /WX /Zc:char8_t,__cplusplus,externConstexpr,hiddenFriend,lambda,referenceBinding,rvalueCast,strictStrings,ternary,throwingNew")
set(_debug_flags "/D_DEBUG /JMC /MTd /Od /Ob0 /RTC1 /Z7")
# /GA (Optimize for Windows Application): using it for a DLL can result in bad code generation.
set(_release_flags "/DNDEBUG /GA /GL /GT /Gw /Gy /guard:cf /guard:ehcont /MT /Zc:inline")
set(_link_flags "/CETCOMPAT /DYNAMICBASE /GUARD:CF /HIGHENTROPYVA /INCREMENTAL:NO /LARGEADDRESSAWARE /LTCG /NOLOGO /NXCOMPAT /OPT:REF /OPT:ICF /OPT:LBR /TSAWARE /WX")

set(CMAKE_C_FLAGS "${_common_flags} /std:c17" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_DEBUG "${_debug_flags}" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_MINSIZEREL "${_release_flags} /O1 /Ob1" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELEASE "${_release_flags} /O2 /Ob3 /Oi" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELWITHDEBINFO "${_release_flags} /O2 /Ob3 /Oi /Z7" CACHE STRING "" FORCE)

set(CMAKE_CXX_STANDARD_LIBRARIES "Kernel32.lib" CACHE STRING "" FORCE)

set(CMAKE_CXX_FLAGS "${_common_flags} /std:c++17" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_DEBUG "${_debug_flags}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_MINSIZEREL "${_release_flags} /O1 /Ob1" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELEASE "${_release_flags} /O2 /Ob3 /Oi" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${_release_flags} /O2 /Ob3 /Oi /Z7" CACHE STRING "" FORCE)

set(CMAKE_RC_FLAGS "-c65001 /DWIN32 /nologo" CACHE STRING "" FORCE)

string(APPEND CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT " /NOLOGO ")
set(CMAKE_EXE_LINKER_FLAGS_MINSIZEREL "${_link_flags}" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${_link_flags}" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${_link_flags} /DEBUG" CACHE STRING "" FORCE)

string(APPEND CMAKE_SHARED_LINKER_FLAGS_DEBUG_INIT " /NOLOGO ")
set(CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL "${_link_flags}" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "${_link_flags}" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "${_link_flags} /DEBUG" CACHE STRING "" FORCE)

string(APPEND CMAKE_STATIC_LINKER_FLAGS_DEBUG_INIT " /NOLOGO /WHOLEARCHIVE ")
string(APPEND CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL_INIT " /NOLOGO /WHOLEARCHIVE ")
string(APPEND CMAKE_STATIC_LINKER_FLAGS_RELEASE_INIT " /NOLOGO /WHOLEARCHIVE ")
string(APPEND CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO_INIT " /NOLOGO /WHOLEARCHIVE ")

unset(_common_flags)
unset(_debug_flags)
unset(_release_flags)
unset(_link_flags)
unset(NTDDI_WIN10_19H1)
